source "https://rubygems.org"

ruby File.read(".ruby-version").chomp

gem "rails", "~> 7.0.8"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.0"
gem "base64", "~> 0.2.0"
gem "bigdecimal", "~> 3.1"
gem "mutex_m", "~> 0.2.0"

gem "flowbite_components", path: "../"

group :development, :test do
  gem "foreman"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
